[package]
name = "recursion-gnark-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
recursion-gnark-ffi = { path = "../ffi" }
clap = { version = "4.5.9", features = ["derive"] }
bincode = "1.3.3"
hex = "*"
